/**
 * @module simplify-engine/color/types
 * @version 1.0.0
 *
 * @description
 * Strongly‑typed color primitives for the Simplify Engine.
 *
 * This module defines the foundational color contracts used across all
 * theming, surfaces, states, and semantic roles. Every type is designed to be:
 *
 * - **Deterministic** — no optionality unless explicitly allowed.
 * - **Rectangular** — every mode and state is fully represented.
 * - **Runtime‑safe** — shapes are predictable and serializable.
 * - **UI‑oriented** — aligned with real component needs (surface, stroke, text).
 *
 * These types form the backbone of the SimplifyTheme contract and ensure
 * consistent color resolution across light, dark, and high‑contrast modes.
 *
 * @see SimplifyTheme
 * @see ModeColor
 * @see SurfaceLayer
 * @see StateColorMap
 */

// ============================================================================
// Theme Modes
// ============================================================================

/**
 * @description
 * Supported UI color modes for the Simplify Engine.
 *
 * These modes correspond directly to CSS variables generated by the
 * theming subsystem. Every color token must define a value for each mode.
 *
 * - `"light"` — Standard light theme.
 * - `"dark"` — Standard dark theme.
 * - `"highContrast"` — Accessibility‑optimized theme variant.
 */
export type ThemeMode = "light" | "dark" | "highContrast";

// ============================================================================
// ModeColor
// ============================================================================

/**
 * @description
 * A color value defined per UI mode.
 *
 * This structure guarantees that every color token is fully specified for
 * all supported modes. It is the smallest atomic color unit in the system.
 *
 * @example
 * const background: ModeColor = {
 *   light: "#ffffff",
 *   dark: "#1a1a1a",
 *   highContrast: "#000000"
 * };
 */
export interface ModeColor {
  light: string;
  dark: string;
  highContrast: string;
}

// ============================================================================
// Color States
// ============================================================================

/**
 * @description
 * Enumerates all supported UI interaction states.
 *
 * These states are used across surfaces, roles, and semantic channels.
 *
 * - `"default"` — Base, idle state.
 * - `"hover"` — Pointer hover.
 * - `"pressed"` — Active press or drag.
 * - `"selected"` — Selected or toggled.
 * - `"disabled"` — Non‑interactive, muted.
 */
export type ColorState =
  | "default"
  | "hover"
  | "pressed"
  | "selected"
  | "disabled";

// ============================================================================
// StateColorMap
// ============================================================================

/**
 * @description
 * A mapping of interaction states to their corresponding ModeColor values.
 *
 * This ensures that every state is fully defined for every mode.
 *
 * @example
 * const buttonBackground: StateColorMap = {
 *   default: { light: "#eee", dark: "#222", highContrast: "#000" },
 *   hover:   { light: "#ddd", dark: "#333", highContrast: "#000" },
 *   pressed: { light: "#ccc", dark: "#444", highContrast: "#000" },
 *   selected:{ light: "#bbb", dark: "#555", highContrast: "#000" },
 *   disabled:{ light: "#f5f5f5", dark: "#111", highContrast: "#000" }
 * };
 */
export type StateColorMap = Record<ColorState, ModeColor>;

// ============================================================================
// SurfaceChannel
// ============================================================================

/**
 * @description
 * A complete set of color channels for a surface element.
 *
 * Each channel (background, foreground, stroke) defines a full set of
 * interaction states. Optional channels allow for richer UI semantics:
 *
 * - `focus` — Focus ring or outline.
 * - `onSurface` — Text/icon color that sits *on* this surface.
 * - `alpha` — Transparency‑based overlays (e.g., scrims, fades).
 *
 * @example
 * const surfaceBackground: SurfaceChannel = {
 *   default: { light: "#fff", dark: "#1a1a1a", highContrast: "#000" },
 *   hover:   { light: "#f7f7f7", dark: "#222", highContrast: "#000" },
 *   pressed: { light: "#eee", dark: "#2a2a2a", highContrast: "#000" },
 *   selected:{ light: "#e5e5e5", dark: "#333", highContrast: "#000" },
 *   disabled:{ light: "#f0f0f0", dark: "#111", highContrast: "#000" },
 *   focus:   { light: "#2684ff", dark: "#4c9aff", highContrast: "#fff" }
 * };
 */
export interface SurfaceChannel {
  default: ModeColor;
  hover: ModeColor;
  pressed: ModeColor;
  selected: ModeColor;
  disabled: ModeColor;

  focus?: ModeColor;
  onSurface?: ModeColor;
  alpha?: ModeColor;
}

// ============================================================================
// SurfaceLayer
// ============================================================================

/**
 * @description
 * A surface layer defines the three primary color channels used in UI
 * rendering:
 *
 * - `background` — The base fill of the surface.
 * - `foreground` — Text, icons, and content that sits on the surface.
 * - `stroke` — Borders, outlines, separators.
 *
 * Each channel contains a full set of interaction states.
 */
export interface SurfaceLayer {
  background: SurfaceChannel;
  foreground: SurfaceChannel;
  stroke: SurfaceChannel;
}

// ============================================================================
// SimplifyTheme
// ============================================================================

/**
 * @description
 * The complete theme contract for the Simplify Engine.
 *
 * A theme is composed of:
 *
 * **Layers** — structural UI surfaces:
 * - `base` — App background.
 * - `surface` — Standard UI surface.
 * - `elevated` — Surfaces with elevation/shadow.
 * - `raised` — Floating or popover surfaces.
 * - `accent` — Brand‑accented surfaces.
 *
 * **State roles** — semantic meaning layers:
 * - `danger`
 * - `warning`
 * - `success`
 * - `info`
 *
 * Each layer and role is a fully rectangular `SurfaceLayer`.
 */
export interface SimplifyTheme {
  layers: {
    base: SurfaceLayer;
    surface: SurfaceLayer;
    elevated: SurfaceLayer;
    raised: SurfaceLayer;
    accent: SurfaceLayer;
  };
  state: {
    danger: SurfaceLayer;
    warning: SurfaceLayer;
    success: SurfaceLayer;
    info: SurfaceLayer;
  };
}

// ============================================================================
// UserTheme
// ============================================================================

/**
 * @description
 * Alias for user‑provided themes. This allows future extension (e.g.,
 * partial themes, theme overrides) without breaking the public API.
 */
export type UserTheme = SimplifyTheme;

// ============================================================================
// Paint
// ============================================================================

/**
 * @description
 * Optional configuration for a `PaintValue`. Currently supports:
 *
 * - `mode` — Explicitly force a specific theme mode during resolution.
 */
export interface PaintOptions {
  mode?: ThemeMode;
}

/**
 * @description
 * A tagged wrapper around a `ModeColor` token. This structure allows the
 * rendering pipeline to detect values that require mode‑aware resolution.
 *
 * - `__paint` — A structural tag used by `isPaint()`.
 * - `token` — The underlying `ModeColor` definition.
 * - `options` — Optional rendering configuration.
 */
export interface PaintValue {
  __paint: true;
  token: ModeColor;
  options?: PaintOptions;
}
